name: Update README with Sequential GIF
on:
  schedule:
    - cron: '*/2 * * * *' # Запуск каждые 5 минут
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run script to update README
        run: |
          python updateReadme.py
